#!/bin/sh

result=0

for file in $(git diff --name-only --cached --diff-filter d); do
    case $file in
	*.rs)
	    rustfmt --check $file
	    if [ $? != 0 ]; then
		echo ${file} needs formatting before commit
		result=1
	    fi
	    ;;
    esac
done

exit $result
