from centos:latest

cmd LD_LIBRARY_PATH=/usr/local/lib /root/.cargo/bin/riffol -f /etc/riffol.conf

run yum install -y gcc git make autoconf automake libtool
run git clone https://github.com/vstakhov/libucl.git && cd libucl && ./autogen.sh && ./configure && make install

run curl https://sh.rustup.rs -sSf | sh -s -- -y
run ~/.cargo/bin/cargo install --git https://github.com/riboseinc/riffol.git

run yum -y install epel-release which sysvinit-tools
copy openvpn-init.sh /riffol/
copy riffol.conf /etc/

